apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app
spec:
  selector:
    matchLabels:
      app: go-sample-app
  replicas: 3
  template:
    metadata:
      labels:
        app: go-sample-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80