apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app
spec:
  selector:
    matchLabels:
      app: go-sample-app
  replicas: 3
  template:
    metadata:
      labels:
        app: go-sample-app
    spec:
      containers:
      - name: go-sample-app  
        image: cavs2016/go-sample-app:1
        ports:
        - containerPort: 80